export const GAME_WIDTH = 640;
export const GAME_HEIGHT = 480;

// Base64 encoded simple pixel art sprites to ensure zero external dependencies
// These are 16x16 or similar scaled up placeholders

// A yellow duck facing right
export const DUCK_SPRITE = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAKlJREFUOE+dkVEKwCAMQ51uJ/b+d2IvNxhIYbS2Px8C8WlS2/qRz7tPB4A6y9+BdQBRwD2wA6oA1kAMoAiwBKIASyAKsAQiAUMgEjAEYgBDoAgwBCIAQyASUAUYAlGAIRAFGAJRgCEQBRgCUYAhEAXYA1GABRAD2ANRgD0QBVgCWYAlkAXYA1mAJZAFWAJZgCWQBVgCWYAlkAVYAlmAJZAFWAJZgCWQBd4X8w8OEh64kQAAAABJRU5ErkJggg==`;

// A brown block for ground
export const GROUND_SPRITE = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAEBJREFUOE9jZGBg+M+AAxYs4qOAD0B9j+A0gG4EskF0A/D6gG4Ashm4DCCbgeswYBrAwMCATwPIDsQ0gG4E3QAA0v4tEY+614wAAAAASUVORK5CYII=`;

// A grey rock/stump
export const OBSTACLE_SPRITE = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAFZJREFUOE9jZGBg+M+AAxYs4qOAD0B9j+A0gG4EskF0A/D6gG4Ashm4DCCbgeswYBoA0wB0OyAbQDeAbgfIDkC3A2Q3gG4HyA5AtwNkNyC7ATkY0A0gOwwA0v4tEa4714wAAAAASUVORK5CYII=`;

// A bread crumb (orange/brown)
export const BREAD_SPRITE = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAAXNSR0IArs4c6QAAADBJREFUKFNjZGBg+M+ABhYs4sMAMoLrAJlINgBdI8wAsgFIA90AkgF0A0gG0A0gGQAAtB8fEdH629AAAAAASUVORK5CYII=`;

export const PRESS_START_FONT = "'Press Start 2P', cursive";
